backend:
  name: git-gateway
media_folder: static/assets
public_folder: assets
collections:
  - name: "site-information"
    label: "Site Information"
    folder: "src/data"
    create: false
    fields:
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Name", name: "name" }
      - { label: "Tagline", name: "tagline" }
      - { label: "Description", name: "description" }
  - name: "events"
    label: "Events"
    folder: "src/data/events"
    create: true
    fields:
      - { label: "Featured Photo", name: "photo", widget: "image" }
      - { label: "Name", name: "title" }
      - { label: "Date", name: "date" }
      - { label: "Description", name: "description" }
      - { label: "Link", name: "link" }
  - name: "team"
    label: "Team"
    folder: "src/data/team"
    create: true
    fields:
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Name", name: "title" }
      - { label: "Role", name: "role" }
      - { label: "Email", name: "email" }
      - { label: "Description", name: "description" }
      - { label: "Link", name: "link" }
  - name: "partner-organizations"
    label: "Partner Organizations"
    folder: "src/data/partner-organizations"
    create: true
    fields:
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Name", name: "title" }
      - { label: "Email", name: "email" }
      - { label: "Description", name: "description" }
      - { label: "Link", name: "link" }
